"""
Search router — internal only (never exposed outside Docker network).

GET /search?q=<query>&user_id=<int>

Called by the Node backend after it has authenticated the user.
Returns a list of file records whose tags match the query terms.
"""
import logging
import mimetypes
import os
from pathlib import Path

from fastapi import APIRouter, HTTPException, Query

from ..config import settings
from ..db import search_tags

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/search", tags=["search"])

# Image extensions that always have thumbnails generated by the Node backend
_THUMBNAIL_EXTENSIONS = frozenset(
    {".jpg", ".jpeg", ".png", ".gif", ".webp", ".bmp",
     ".tiff", ".tif", ".heic", ".heif", ".dng", ".nef",
     ".cr2", ".cr3", ".arw", ".raf"}
)


@router.get("")
def search_files(
    q: str = Query(..., min_length=1, description="Search query"),
    user_id: int = Query(..., description="Authenticated user's DB id"),
    username: str = Query(..., description="Authenticated user's username"),
):
    """
    Return files and directories matching the search query by tag or name/path.
    """
    query_str = q.strip()
    if not query_str:
        raise HTTPException(status_code=400, detail="Query cannot be empty")

    # 1. Fetch DB-tagged results (these match tags or file paths already tagged)
    rows = search_tags(user_id, query_str)
    
    # 2. Map tagged results by relative path for quick lookup and deduplication
    results_map = {}
    user_root = Path(settings.STORAGE_ROOT) / username
    
    for row in rows:
        rel_path = row["file_path"]
        abs_path = user_root / rel_path
        if not abs_path.exists():
            continue
            
        ext = abs_path.suffix.lower()
        mime = mimetypes.guess_type(str(abs_path))[0]
        stat = abs_path.stat()
        
        results_map[rel_path] = {
            "name": abs_path.name,
            "path": rel_path,
            "type": "file",
            "size": stat.st_size,
            "mtime": stat.st_mtime,
            "mimeType": mime,
            "hasThumbnail": ext in _THUMBNAIL_EXTENSIONS,
            "tags": row["tags"],
            "relevance": row.get("relevance", 1) + 1,  # Boost relevance for DB-tagged matches
        }

    # 3. Walk the user's directory on disk to find matching files/directories
    # Split query into words to match as substrings
    words = [w.lower().strip() for w in query_str.split() if w.strip()]
    
    if words and user_root.exists():
        for root, dirs, files in os.walk(user_root):
            # Skip hidden directories
            dirs[:] = [d for d in dirs if not d.startswith(".")]
            
            # Check directories
            for dname in dirs:
                # If dname matches any query word as substring
                if any(w in dname.lower() for w in words):
                    abs_dir = Path(root) / dname
                    rel_dir = str(abs_dir.relative_to(user_root)).replace("\\", "/")
                    if rel_dir not in results_map:
                        stat = abs_dir.stat()
                        results_map[rel_dir] = {
                            "name": dname,
                            "path": rel_dir,
                            "type": "directory",
                            "size": None,
                            "mtime": stat.st_mtime,
                            "mimeType": None,
                            "hasThumbnail": False,
                            "tags": [],
                            "relevance": 1,
                        }
            
            # Check files
            for fname in files:
                if fname.startswith("."):
                    continue
                # If fname matches any query word as substring
                if any(w in fname.lower() for w in words):
                    abs_file = Path(root) / fname
                    rel_file = str(abs_file.relative_to(user_root)).replace("\\", "/")
                    if rel_file not in results_map:
                        stat = abs_file.stat()
                        ext = abs_file.suffix.lower()
                        mime = mimetypes.guess_type(str(abs_file))[0]
                        # Videos or images can have thumbnails
                        is_image_or_video = ext in _THUMBNAIL_EXTENSIONS or (mime and (mime.startswith("image/") or mime.startswith("video/")))
                        results_map[rel_file] = {
                            "name": fname,
                            "path": rel_file,
                            "type": "file",
                            "size": stat.st_size,
                            "mtime": stat.st_mtime,
                            "mimeType": mime,
                            "hasThumbnail": is_image_or_video,
                            "tags": [],
                            "relevance": 1,
                        }

    # 4. Sort results by relevance (highest first) and date (newest first)
    sorted_results = list(results_map.values())
    sorted_results.sort(key=lambda x: (x["relevance"], x["mtime"]), reverse=True)

    # Remove relevance field from final response to match expected frontend schema
    for r in sorted_results:
        r.pop("relevance", None)

    return {"results": sorted_results, "total": len(sorted_results), "query": q}
